<?php
$z[0]=Array("field","",112,140);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",151,180);
$z[1][4]['name']="typename";
$z[2]=Array("field","",211,240);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n            <dd><a href='[field:typeurl/]' title='[field:typename/]' >[field:typename/]</a></dd>\r\n            ",281,548);
$z[3][4]['type']="son";
$z[3][4]['row']="4";
$z[3][4]['currentstyle']="<dd><a href='~typelink~' ~rel~><span>~typename~</span></a></dd>";

?>