<li class="CON--top-rs" style="width:310px;">
          <dt class="fl" style="width:120px;"> <a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]" width="120" height="80"/></a> </dt>
          <dd class="fr" style="width:175px;">
            <h2 style="width:175px;"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
            <p style="height:45px;">[field:info/]...</p>
          </dd>
          <div class="clear"></div>
        </li>