<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150928/1-15092Q30056.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150928/1-15092Q30056.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="380";
$z[1][4]['height']="280";
$z[2]=Array("img"," /uploads/allimg/150928/1-15092Q30057.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/150928/1-15092Q30057.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="380";
$z[2][4]['height']="280";
$z[3]=Array("img"," /uploads/allimg/150928/1-15092Q30057-50.jpg ",387,538);
$z[3][4]['ddimg']="/uploads/allimg/150928/1-15092Q30057-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="380";
$z[3][4]['height']="280";

?>