<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:gg itemname="包装规格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gg>
<field:bzq itemname="保质期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bzq>
<field:tj itemname="储存条件" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tj>
<field:yt itemname="用途" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yt>
