<?php
$z[0]=Array("global","",750,776);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",846,872);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",881,907);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1032,1057);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1577,1603);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channelartlist","\r\n        <li class=\"nav-line\"></li>\r\n        <li id='nav_[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global]' style='width:134px;' ><a href='{dede:field name='typeurl'/}' 0 title='{dede:field name='typename'/}' class='hover-none nav'><span>{dede:field name='typename'/}</span></a>\r\n          <dl>\r\n            {dede:channel type='son' row='4' currentstyle=\"\r\n            <dd><a href='~typelink~' ~rel~><span>~typename~</span></a></dd>\r\n            \"}\r\n            <dd><a href='[field:typeurl/]' title='[field:typename/]' >[field:typename/]</a></dd>\r\n            {/dede:channel}\r\n          </dl>\r\n        </li>\r\n        ",1664,2356);
$z[5][4]['typeid']="top";
$z[6]=Array("type","\r\n        <li id='nav_10' style='width:133px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",2402,2611);
$z[6][4]['typeid']="5";

?>