<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",715,750);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",891,949);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n        <dl class=\"list-none navnow\">\r\n          <dt id='part2_6'><a href='[field:typeurl/]'  title='[field:typename/]'><span>[field:typename/]</span></a></dt>\r\n        </dl>\r\n        ",1051,1461);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<dl class='list-none navnow'> <dt id='part2_6' class='on'><a href='~typelink~' class='zm'><span>~typename~</span></a></dt> </dl>";
$z[7]=Array("field","",2294,2323);
$z[7][4]['name']="position";
$z[8]=Array("field","",2345,2370);
$z[8][4]['name']="name";
$z[9]=Array("field","",2474,2495);
$z[9][4]['name']="content";
$z[10]=Array("include","",2589,2626);
$z[10][4]['filename']="footer.htm";

?>